version: "3.9"

services:
  postgres:
    build: .
    container_name: brand_tracker_db
    environment:
      POSTGRES_DB: trackerdb
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    restart: always

volumes:
  db_data:
